/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathgame.gui;

import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import javax.swing.JTextField;
import mathgame.game.GameMode;
import mathgame.util.calculator.Calculator;
import mathgame.mediator.MathGameMediator;
import java.util.List;
import java.util.LinkedList;

/**
 *
 * @author Feilan
 */
public class Screens extends javax.swing.JFrame {

    /**
     * Creates new form Screens
     * @param mediator
     */
    public Screens(MathGameMediator mediator) {        
        this.mediator = mediator;
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>                
        
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        screens = new javax.swing.JPanel();
        startScreen = new javax.swing.JPanel();
        algebraButton = new javax.swing.JButton();
        geometryButton = new javax.swing.JButton();
        algebraStatsLabel = new javax.swing.JLabel();
        geometryStatsLabel = new javax.swing.JLabel();
        trigButton = new javax.swing.JButton();
        eraseStatsButton = new javax.swing.JButton();
        trigStatsLabel = new javax.swing.JLabel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        gameScreen = new javax.swing.JPanel();
        questionSplitPane = new javax.swing.JSplitPane();
        questionContent = new javax.swing.JPanel();
        answerContent = new javax.swing.JPanel();
        quitButton = new javax.swing.JButton();
        calculatorTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        screens.setAutoscrolls(true);
        screens.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        screens.setLayout(new java.awt.CardLayout());

        startScreen.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        startScreen.setLayout(new java.awt.GridBagLayout());

        algebraButton.setText("Algebra/Functions");
        algebraButton.setPreferredSize(new java.awt.Dimension(100, 31));
        algebraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algebraButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        startScreen.add(algebraButton, gridBagConstraints);

        geometryButton.setText("Geometry");
        geometryButton.setPreferredSize(new java.awt.Dimension(100, 31));
        geometryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geometryButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        startScreen.add(geometryButton, gridBagConstraints);

        algebraStatsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        algebraStatsLabel.setText("jLabel1");
        algebraStatsLabel.setFocusable(false);
        algebraStatsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.3;
        startScreen.add(algebraStatsLabel, gridBagConstraints);

        geometryStatsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        geometryStatsLabel.setText("jLabel2");
        geometryStatsLabel.setFocusable(false);
        geometryStatsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.3;
        startScreen.add(geometryStatsLabel, gridBagConstraints);

        trigButton.setText("Trigonometry");
        trigButton.setPreferredSize(new java.awt.Dimension(100, 31));
        trigButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trigButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        startScreen.add(trigButton, gridBagConstraints);

        eraseStatsButton.setText("Erase Stats");
        eraseStatsButton.setPreferredSize(new java.awt.Dimension(100, 31));
        eraseStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eraseStatsButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.3;
        startScreen.add(eraseStatsButton, gridBagConstraints);

        trigStatsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trigStatsLabel.setText("jLabel3");
        trigStatsLabel.setFocusable(false);
        trigStatsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.3;
        startScreen.add(trigStatsLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        startScreen.add(filler11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        startScreen.add(filler12, gridBagConstraints);

        screens.add(startScreen, "startScreen");

        gameScreen.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        gameScreen.setLayout(new java.awt.BorderLayout(0, 10));

        questionSplitPane.setResizeWeight(0.5);
        questionSplitPane.setToolTipText("");
        questionSplitPane.setEnabled(false);

        javax.swing.GroupLayout questionContentLayout = new javax.swing.GroupLayout(questionContent);
        questionContent.setLayout(questionContentLayout);
        questionContentLayout.setHorizontalGroup(
            questionContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        questionContentLayout.setVerticalGroup(
            questionContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        questionSplitPane.setLeftComponent(questionContent);

        javax.swing.GroupLayout answerContentLayout = new javax.swing.GroupLayout(answerContent);
        answerContent.setLayout(answerContentLayout);
        answerContentLayout.setHorizontalGroup(
            answerContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );
        answerContentLayout.setVerticalGroup(
            answerContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );

        questionSplitPane.setRightComponent(answerContent);

        gameScreen.add(questionSplitPane, java.awt.BorderLayout.CENTER);

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        gameScreen.add(quitButton, java.awt.BorderLayout.PAGE_END);

        calculatorTextField.setToolTipText("Calculator");
        calculatorTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                calculatorTextFieldKeyTyped(evt);
            }
        });
        gameScreen.add(calculatorTextField, java.awt.BorderLayout.PAGE_START);

        screens.add(gameScreen, "gameScreen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(screens, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(screens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void algebraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algebraButtonActionPerformed
        showGameScreen(GameMode.ALGEBRA);
    }//GEN-LAST:event_algebraButtonActionPerformed

    private void geometryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geometryButtonActionPerformed
        showGameScreen(GameMode.GEOMETRY);
    }//GEN-LAST:event_geometryButtonActionPerformed

    private void trigButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trigButtonActionPerformed
        showGameScreen(GameMode.TRIGONOMETRY);
    }//GEN-LAST:event_trigButtonActionPerformed

    private void eraseStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eraseStatsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eraseStatsButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        showStartScreen();
    }//GEN-LAST:event_quitButtonActionPerformed

    private void calculatorTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calculatorTextFieldKeyTyped
        JTextField textField = (JTextField) evt.getSource();
        
        if (evt.getKeyChar() == KeyEvent.VK_ENTER && !textField.getText().equals("")) {
            String answer = Calculator.eval(textField.getText(), false);            
            
            /*javafx.embed.swing.JFXPanel panel = new javafx.embed.swing.JFXPanel();
            javafx.scene.chart.NumberAxis xAxis = new javafx.scene.chart.NumberAxis(-10.0, 10.0, 1.0);
            javafx.scene.chart.NumberAxis yAxis = new javafx.scene.chart.NumberAxis(-10.0, 10.0, 1.0);
            FunctionPlot fp = new FunctionPlot(xAxis, yAxis, )
            panel.add(fp);
            questionContent.add(fp);*/
                    
            textField.setText((answer == null) ? "Error" : answer);
        }
    }//GEN-LAST:event_calculatorTextFieldKeyTyped
    
    private void showGameScreen(GameMode gameMode) {
        CardLayout card = (CardLayout) screens.getLayout();
        card.show(screens, "gameScreen");
        mediator.gameStarted(gameMode);
    }
    
    private void showStartScreen() {
        CardLayout card = (CardLayout) screens.getLayout();
        card.show(screens, "startScreen");        
        mediator.gameEnded();
    }

    private MathGameMediator mediator;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton algebraButton;
    private javax.swing.JLabel algebraStatsLabel;
    private javax.swing.JPanel answerContent;
    private javax.swing.JTextField calculatorTextField;
    private javax.swing.JButton eraseStatsButton;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.JPanel gameScreen;
    private javax.swing.JButton geometryButton;
    private javax.swing.JLabel geometryStatsLabel;
    private javax.swing.JPanel questionContent;
    private javax.swing.JSplitPane questionSplitPane;
    private javax.swing.JButton quitButton;
    private javax.swing.JPanel screens;
    private javax.swing.JPanel startScreen;
    private javax.swing.JButton trigButton;
    private javax.swing.JLabel trigStatsLabel;
    // End of variables declaration//GEN-END:variables
}
